name: 'NewRelic comparison functionality'
description: 'Provide a description here'
author: 'core3'
branding:
  icon: 'crosshair'
  color: 'blue'
inputs:
  input_file: # change this
    required: true
    description: 'input file in json format with wcs measure results'
  output_file: # change this
    required: true
    description: 'output file name'
  nr_query_id: # change this
    required: true
    description: 'newrelic query id'
  nr_account_id: # change this
    required: true
    description: 'newrelic account id'
  measured_os:
    required: false
    description: 'os to measure on: "windows/linux/mac" '
    default: 'linux'

runs:
  using: 'node12'
  main: 'dist/index.js'
